### ISSUE TITLE
How can this be added to home assistant. I am getting error with the HTU21 platform. 

### ISSUE THREAD

**Issue by pumatrax** [SolderedElectronics/SHT21-Arduino-Library#6]
Error i2cRead returned Error 263 using SHT21 with ESP32 in Home Assistant using ESPhome. I wanted to try this library.

**Comment by rsoric** [comment]
Hi @pumatrax 

Which board and board definition are you using? Please share more info about your problem and we'll see what we can do.

**Comment by rsoric** [comment]
Closing the issue as there's no more activity after a while
